language: objective-c
osx_image: xcode9.3
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - make test_osx SCHEME=processing_mac_tests SDK=macosx
