language: objective-c
osx_image: xcode10.2
branches:
  only:
    - master
notifications:
  email: false
install:
  - brew install clang-format
script:
  - xcodebuild -workspace processing_mac.xcworkspace -scheme processing_mac_tests -configuration Debug OBJROOT=build -sdk macosx clean test
  - xcodebuild -workspace processing_ios.xcworkspace -scheme processing_ios_tests -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.2' clean test
