language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
notifications:
  email: false
script:
  - xcodebuild -project cpp_utils_test/cpp_utils_test.xcodeproj -scheme cpp_utils_test_mac -configuration Debug OBJROOT=build -sdk macosx clean test
  - xcodebuild -project cpp_utils_test/cpp_utils_test.xcodeproj -scheme cpp_utils_test_ios -configuration Debug OBJROOT=build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean test
